---
title: "Clasificación de cuidadores para habitos de vida saludable"
author: "Duban Romero"
date: "`r Sys.time()`"
output:
  html_document: default
  word_document: default
editor_options:
  chunk_output_type: inline
---

```{r, include=FALSE}
source("https://raw.githubusercontent.com/rduban/Rfunctions_DR/main/R%20functions.R")
library(readxl)
library(tidyverse)
library(knitr)
library(factoextra)
library(NbClust)
library(apcluster)
library(patchwork)
```

```{r, include=FALSE}
pretest<-read_csv2("pretest_calificado.csv")[-1]

variables<- c("relaciones","actividad","descanso","nutricion","oral","sexualidad","sustancias","optimismo","ambiente","movilidad","estrato_gr")

demogra<- c("educacion_gr","ocupacion_gr","contexto","parentesco","etnia","familia","edadEncuestado","edad_meses","sexo","DineroAprox")

x<-ifelse(rowSums(is.na(pretest[variables]))>0,1,0)

pretest<- pretest[x==0 & pretest$estrato_gr==1,c(variables,demogra)]

pretest$ID<-1:nrow(pretest)

```


# Muestra
```{r}
dim(pretest)
table(pretest$sexo)
prop.table(table(pretest$sexo))
table(pretest$educacion_gr)
prop.table(table(pretest$educacion_gr))
table(pretest$ocupacion_gr)
prop.table(table(pretest$ocupacion_gr))
table(pretest$estrato_gr)
prop.table(table(pretest$estrato_gr))
table(pretest$contexto)
prop.table(table(pretest$contexto))
table(pretest$parentesco)
prop.table(table(pretest$parentesco))
table(pretest$etnia)
prop.table(table(pretest$etnia))
table(pretest$familia)
prop.table(table(pretest$familia))
table(pretest$estrato_gr)
prop.table(table(pretest$estrato_gr))

# edad del cuidador
pretest$edadEncuestado<- ifelse(!(pretest$edadEncuestado %in% 18:100),median(pretest$edadEncuestado),pretest$edadEncuestado)
summary(pretest$edadEncuestado);sd(pretest$edadEncuestado,na.rm = T)

# Edad del niño
pretest$edad_meses<- ifelse(!(pretest$edad_meses %in% 0:72),median(pretest$edad_meses),pretest$edad_meses)
summary(pretest$edad_meses);sd(pretest$edad_meses,na.rm = T)

# ingresos
pretest$DineroAprox<-as.numeric(pretest$DineroAprox)
pretest$DineroAprox<- ifelse(pretest$DineroAprox>2000000,NA,pretest$DineroAprox)
summary(pretest$DineroAprox)
```

**Descriptivos por practicas de cuidado**

```{r,echo=FALSE}
data.frame(apply(pretest[1:11],2,function(x){
 round(cbind(mean(x),sd(x)),2)
}))->a
row.names(a)<-c("M","DE")
a %>% kable()
```

# EDA

```{r}
round(cor((pretest[1:10])),2) %>% kable()
```

# K-means
```{r}
a<- get_dist(pretest[1:10], method = "euclidean")

set.seed(123)

numclust<-NbClust::NbClust(pretest[1:10], distance = "euclidean", min.nc=2, max.nc=5, method = "kmeans", index = "all")

t(numclust$Best.nc)

# extraer 3 clusters

clust <- kmeans(a, centers = 3, nstart = 25)
fviz_cluster(clust, data = pretest[1:10])
sum(clust$betweenss)/clust$totss
```

De acuerdo a la grafica, se hace necesario eliminar las observaciones que quedaron en el cluster 2 ya que al parecer es un cluster compuesto por la información residual de los otros. (532,510,43)

```{r}
set.seed(123)

a<- get_dist(pretest[-c(35,134,188,500,592),1:10],
             method = "euclidean")

numclust<-NbClust::NbClust(pretest[-c(35,134,188,500,592),1:10],
                           distance = "euclidean", min.nc=2, max.nc=5,
                           method = "kmeans", index = "all")

```

```{r,include=FALSE}
x<-data.frame(t(numclust$Best.nc))
x$criteria<-rownames(x)

x %>%
  ggplot(aes(x=Number_clusters,y=criteria))+
  geom_bar(stat="identity",fill=colores[1])+
  labs(x="Clusters' number",y="Criteria")+
  theme(legend.position = "none",
          axis.text = element_text(face="bold"),
          panel.background = element_rect(fill = "white")) -> f1

```


```{r,include=F}
y<-c(NA)
for(i in 1:10){
x<-kmeans(a, centers = i, nstart = 25)
y[i]<-sum(x$betweenss)/x$totss
}

x1<-data.frame(Clusters=c(1:10),y)

x1 %>%
  ggplot(aes(x=Clusters,y=(y)))+
  geom_point(color="black",size=2.5)+
  geom_line(color=colores[1],linewidth=1)+
  scale_y_continuous(name="Variance explained",breaks = seq(0,1,0.05))+
  scale_x_continuous("Clusters' number",breaks=seq(1,10,1))+
  theme(legend.position = "bottom",
          axis.text = element_text(face="bold"),
          panel.background = element_rect(fill = "white")) ->f2
```


```{r}

# extraer 3 clusters

clust<-kmeans(a, centers = 3, nstart = 25) 
fviz_cluster(clust, data = pretest[-c(35,134,188,500,592),1:10])

sum(clust$betweenss)/clust$totss
pretest$clustKmean<-NA
pretest[-c(35,134,188,500,592),]$clustKmean<- clust$cluster
pretest$clustKmean<- factor(pretest$clustKmean,levels = c(2,1,3),labels = c(1:3))
```


```{r,include=FALSE}
x<-data.frame(t(clust$centers))

y<-data.frame(apply(x[1:3],2,function(z){
  tapply(z,clust$cluster,mean)}))

x<-rbind(x,y)

x$cluster=c(clust$cluster,NA,NA,NA)

x$centroide<-c(rep(FALSE,(nrow(x)-3)),rep(TRUE,3))

x %>%
  ggplot(aes(x=X2,y=X3))+
  geom_point(aes(color=factor(cluster),shape=centroide==TRUE,size=centroide==T))+
  scale_color_manual("Cluster",values = colores)+
  scale_size_manual("",values=c(2,5))+
  labs(x="Dimension 1",y="Dimension 2")+
  theme(legend.position = "none",
          axis.text = element_text(face="bold"),
          panel.background = element_rect(fill = "white"))->f3
```

```{r,echo=FALSE,fig.height=8,fig.width=8}
(f1+f2)/f3+plot_annotation(tag_levels = "A")
```

```{r}
prop.table(table(pretest$clustKmean))
```

# Visualizacion

Visualizacion Kmeans
```{r,include=FALSE}
(a<-data.frame(t(apply(pretest[1:10],2,function(x){tapply(x,pretest$clustKmean,mean)}))))
a$escala<-row.names(a)
a<-gather(a,key="grupo",value="promedio",-escala)
a$escala<- factor(a$escala,levels = names(pretest)[1:10])
```

```{r}
a %>%
  ggplot(aes(x=escala,y=promedio,group=grupo))+
  geom_point(aes(color=grupo),size=2.5)+
  geom_line(aes(color=grupo),size=1.2)+
  scale_x_discrete(name="Scale",labels=c("relaciones"="IR","actividad"="PA",
                                         "descanso"="SL","nutricion"="NU","oral"="OH",
                                        "sexualidad"="SH","sustancias"="SA","optimismo"="OP",
                                         "ambiente"="EN","movilidad"="MO"))+
  scale_y_continuous(name="Mean",breaks = seq(0,5,0.5))+
  scale_color_manual("Cluster",values=colores,labels=1:3)+
  theme(legend.position = "bottom",
          axis.text = element_text(face="bold"),
          panel.background = element_rect(fill = "white"))
```


# Comparaciones

```{r,echo=FALSE}
modelo<-NULL

modelo$relaciones<-aov(data=pretest,relaciones~factor(clustKmean))
modelo$actividad<-aov(data=pretest,actividad~factor(clustKmean))
modelo$descanso<-aov(data=pretest,descanso~factor(clustKmean))
modelo$nutricion<-aov(data=pretest,nutricion~factor(clustKmean))
modelo$oral<-aov(data=pretest,oral~factor(clustKmean))
modelo$sexualidad<-aov(data=pretest,sexualidad~factor(clustKmean))
modelo$sustancias<-aov(data=pretest,sustancias~factor(clustKmean))
modelo$optimismo<-aov(data=pretest,optimismo~factor(clustKmean))
modelo$ambiente<-aov(data=pretest,ambiente~factor(clustKmean))
modelo$movilidad<-aov(data=pretest,movilidad~factor(clustKmean))
kable(my_anova2x2(modelo,level=1))
```

```{r,echo=FALSE}
x1<-as.vector(t(apply(pretest[1:10],2,function(x){
round(tapply(x,pretest$clustKmean,mean),2)
})))

x2<-as.vector(t(apply(pretest[1:10],2,function(x){
round(tapply(x,pretest$clustKmean,sd),2)
})))

x3<-paste0(x1," ","(",x2,")")

x<-data.frame(matrix(x3,ncol = 3,byrow = F))
dimnames(x)<-list(names(pretest)[1:10],paste("Grupo",1:3))

x
```


# Asociaciones

```{r,echo=FALSE}
apply(pretest[demogra[-10]],2,function(x){
  chisq.test(pretest$clustKmean,x)
})
```

```{r,echo=FALSE}
x<-table(pretest$clustKmean,pretest$educacion_gr)
t(x)/colSums(x)
x<-data.frame(t(x)/colSums(x))
```

```{r,include=FALSE}
x %>% 
  ggplot(aes(x=Var1,y=Freq,fill=Var2))+
  geom_bar(stat="identity")+
  scale_fill_manual("Cluster",values=colores,labels=1:3)+
  scale_x_discrete("Education level",labels=c("No universidad"="No university",
                                         "Universidad"="University"))+
  scale_y_continuous("Proportion",breaks=seq(0,1,.1))+
  theme(legend.position = "bottom",
          axis.text = element_text(face="bold"),
          panel.background = element_rect(fill = "white"))->x1


```


```{r,echo=FALSE}
x<-table(pretest$clustKmean,pretest$contexto)
t(x)/colSums(x)
x<-data.frame(t(x)/colSums(x))
```

```{r,include=FALSE}
x %>% 
  ggplot(aes(x=Var1,y=Freq,fill=Var2))+
  geom_bar(stat="identity")+
  scale_fill_manual("Cluster",values=colores,labels=1:3)+
  scale_x_discrete("Living area",labels=c("rural"="Rural",
                                         "urbano"="Urban"))+
  scale_y_continuous("",breaks=seq(0,1,.1))+
  theme(legend.position = "bottom",
          axis.text = element_text(face="bold"),
          panel.background = element_rect(fill = "white"))->x2
```


```{r,echo=FALSE}
x1+x2 + plot_layout(guides = "collect") &
  theme(legend.position='bottom') &
  plot_annotation(tag_levels = "A")
```



